default_platform(:ios)

platform :ios do

    desc "Create certs"
    lane :create_certs do
        create_keychain(
            default_keychain: true,
            name: "mykeychain",
            password: ENV["KEYCHAIN_PASSWORD"],
            unlock: true,
            timeout: 180
        )
        match(
            type: "adhoc",
            keychain_name: "mykeychain",
            keychain_password: ENV["KEYCHAIN_PASSWORD"],
            git_branch: "match-certs",
            git_basic_authorization: Base64.strict_encode64("tri-star:#{ENV['GITHUB_TOKEN']}"),
            clone_branch_directly: true,
            output_path: "ios/fastlane",
            shallow_clone: true
        )
        slack(
            message: "Process complete.",
            slack_url: ENV["SLACK_URL"]
        )
    end

    desc "Archive AdHoc and send to Firebase"
    lane :adhoc do
        create_keychain(
            default_keychain: true,
            name: "mykeychain",
            password: ENV["KEYCHAIN_PASSWORD"],
            unlock: true,
            timeout: 180
        )
        match(
            readonly: true,
            type: "adhoc",
            keychain_name: "mykeychain",
            keychain_password: ENV["KEYCHAIN_PASSWORD"],
            git_branch: "match-certs",
            git_basic_authorization: Base64.strict_encode64("tri-star:#{ENV['GITHUB_TOKEN']}"),
            clone_branch_directly: true,
            shallow_clone: true
        )
        build_app(workspace: "Runner.xcworkspace",
            scheme: "Runner",
            configuration: "Release",
            clean: true,
            export_options: {
            method: "ad-hoc"
        })
        firebase_app_distribution(
            app: "whisimicalendar",
            groups: "developer",
            release_notes: "test",
            firebase_cli_path: `which firebase`.strip()
        )
        slack(
            message: "ベータ版が配信されました\nhttps://appdistribution.firebase.dev/app_distro/projects",
            slack_url: ENV["SLACK_URL"]
        )
    end

end